[package]
name = "crypto-msg-parser"
version = "2.5.8"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2021"
description = "Parse websocket messages from cryptocurreny exchanges"
license = "Apache-2.0"
repository = "https://github.com/crypto-crawler/crypto-crawler-rs/tree/main/crypto-msg-parser"
keywords = ["cryptocurrency", "blockchain", "trading"]

[dependencies]
chrono = "0.4.19"
crypto-contract-value = "1.5.0"
crypto-market-type = "1.1.1"
crypto-msg-type = "1.0.7"
crypto-pair = "2.2.11"
if_chain = "1.0.2"
once_cell = "1.12.0"
reqwest = { version = "0.11.11", features = ["blocking", "gzip"] }
simple-error = "0.2.3"
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.82"
strum = "0.24.1"
strum_macros = "0.24.2"
