[package]
name = "crypto-ws-client"
version = "2.4.5"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2018"
description   = "A versatile websocket client that supports many cryptocurrency exchanges."
license = "Apache-2.0"
repository = "https://github.com/soulmachine/crypto-crawler-rs/tree/main/crypto-ws-client"
keywords = ["cryptocurrency", "blockchain", "trading", "websocket"]

[dependencies]
flate2 = "1"
lazy_static = "1"
log = "0.4"
reqwest = { version = "0.11", features = ["blocking", "gzip"] }
serde_json = "1"
tungstenite = { version = "0.13", default-features = false, features = ["rustls-tls"] }
http = "0.2"
rustls = "0.19.0"
webpki = "0.21.4"
webpki-roots = "0.21.0"
