[package]
name = "crypto-markets"
version = "1.2.7"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2021"
description   = "Fetch trading markets from a cryptocurrency exchange"
license = "Apache-2.0"
repository = "https://github.com/crypto-crawler/crypto-crawler-rs/tree/main/crypto-markets"
keywords = ["cryptocurrency", "blockchain", "trading"]

[dependencies]
chrono = "0.4.19"
crypto-market-type = { git="https://github.com/wmjtyd/crypto-crawler-rs" } 
crypto-pair = { git="https://github.com/wmjtyd/crypto-crawler-rs" }
reqwest = { version = "0.11.11", features = ["blocking", "gzip", "socks"] }
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.82"

[dev_dependencies]
crypto-contract-value = { git="https://github.com/wmjtyd/crypto-crawler-rs" } 
test-case = "1"
