[package]
name = "crypto-crawler"
version = "4.4.9"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2021"
description   = "A rock-solid cryprocurrency crawler."
license = "Apache-2.0"
repository = "https://github.com/crypto-crawler/crypto-crawler-rs/tree/main/crypto-crawler"
keywords = ["cryptocurrency", "blockchain", "trading"]

[dependencies]
crypto-markets = "1.3.1"
crypto-market-type = "1.1.1"
crypto-msg-parser = "2.6.1"
crypto-msg-type = "1.0.8"
crypto-pair = "2.2.11"
crypto-rest-client = "0.9.3"
crypto-ws-client = "4.11.6"
fslock = "0.2.1"
once_cell = "1.13.0"
log = "0.4.17"
rand = "0.8.5"
reqwest = { version = "0.11.11", features = ["blocking", "gzip"] }
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.82"
tokio = { version = "1.19.2", features = ["macros", "rt-multi-thread", "sync", "time"] }

[dev_dependencies]
env_logger = "0.9"
test-case = "1"
tokio = { version = "1", features = ["test-util"] }
