[package]
name = "crypto-crawler"
version = "1.6.4"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2018"
description   = "A rock-solid cryprocurrency crawler."
license = "Apache-2.0"
repository = "https://github.com/soulmachine/crypto-crawler-rs/tree/main/crypto-crawler"
keywords = ["cryptocurrency", "blockchain", "trading"]

[dependencies]
crypto-markets = "0.6.7"
crypto-rest-client = "0.6.3"
crypto-ws-client = "2.4.9"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
strum = "0.20"
strum_macros = "0.20"

[dev_dependencies]
test-case = "1"
