[package]
name = "crypto-rest-client"
version = "0.9.4"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2021"
description   = "An RESTful client for all cryptocurrency exchanges."
license = "Apache-2.0"
repository = "https://github.com/crypto-crawler/crypto-crawler-rs/tree/main/crypto-rest-client"
keywords = ["cryptocurrency", "blockchain", "trading"]

[dependencies]
crypto-market-type = { path = "../crypto-market-type" }
once_cell = "1.13.0"
log = "0.4.17"
regex = "1.6.0"
reqwest = { version = "0.11.11", features = ["blocking", "gzip", "socks"] }
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.82"

[dev_dependencies]
test-case = "1"
