[package]
name = "crypto-pair"
version = "2.2.9"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2021"
description = "Parse exchange-specific symbols to unified format"
license = "Apache-2.0"
repository = "https://github.com/crypto-crawler/crypto-crawler-rs/tree/main/crypto-pair"
homepage = "https://github.com/crypto-crawler/crypto-crawler-rs/tree/main/crypto-pair"

[dependencies]
crypto-market-type = { git="https://github.com/wmjtyd/crypto-crawler-rs" }
once_cell = "1.12.0"
reqwest = { version = "0.11.10", features = ["blocking", "gzip"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
